# Generated by Django 6.0.3 on 2026-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('loyalty_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_rupee', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('redeem_value_per_point', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('minimum_points_to_redeem', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('manager_approval_required', models.BooleanField(default=True)),
            ],
        ),
    ]
