# Generated by Django 6.0.3 on 2026-04-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('swiggy', 'Swiggy'), ('zomato', 'Zomato'), ('ondc', 'ONDC'), ('manual', 'Manual')], max_length=20)),
                ('external_order_id', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('mapped_items', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('received', 'Received'), ('mapped', 'Mapped'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'unique_together': {('source', 'external_order_id')},
            },
        ),
    ]
